version: 0.0
os: linux
files:
  - source: /docker-python-app
    destination: /home/ec2-user/myapp
hooks:
  BeforeInstall:
    - location: my_files/before.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: my_files/after.sh
      timeout: 300
      runas: root
