version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...


  build:
    commands:
      - echo Build started on date
      - echo Building the Docker image using Docker Compose...
      - docker-compose build
      # - docker tag python-docker-app:latest debjyoti12/docker-python-app:latest

  post_build:
    commands:
      - echo Build completed on date
      - docker tag docker-python-repo santanurajbhar/docker-python-app:latest
      - docker login -u santanurajbhar -p 1234@santanu
      - echo Pushing the Docker image to Docker Hub...
      - docker push santanurajbhar/docker-python-app:latest
